CREATE ROLE web LOGIN ENCRYPTED PASSWORD 'md5b2f3841c032b78c3686b9de01c6a6ed7' VALID UNTIL 'infinity';
CREATE DATABASE web WITH OWNER = web ENCODING = 'UTF8' TEMPLATE=template0 TABLESPACE = pg_default LC_COLLATE = 'ru_UA.UTF-8' LC_CTYPE = 'ru_UA.UTF-8' CONNECTION LIMIT = -1;
